### ISSUE TITLE
does the 2016 version work on gmod?

### ISSUE THREAD

**Issue by Heldex** [MFSiNC/HAC#4]
does the 2016 version work on gmod?
thanks

**Comment by MFSiNC** [comment]
Hi, it does not work, as the lists were removed prior to uploading, and certain functions are handled by the HeX's Server Plugins system such as loading files in the right order.

You'd need to recreate the white/black lists, and sort out the filesystem.
I think it also only works on Windows 2003, and expects Dropbox to exist on the desktop etc.

It was uploaded more for people to review the code, rather than to use.
